/*
 * May 12th, 2020
 * Erika Graham
 * Type Casting
 */

/**
 *
 * @author kikag
 */
public class FrmTypeCasting extends javax.swing.JFrame {

    /**
     * Creates new form FrmTypeCasting
     */
    public FrmTypeCasting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblInstruction1 = new javax.swing.JLabel();
        txtQuest1 = new javax.swing.JTextField();
        lblQuest1Out = new javax.swing.JLabel();
        lblInstruction2 = new javax.swing.JLabel();
        txtQuest2 = new javax.swing.JTextField();
        lblQuestion2Out = new javax.swing.JLabel();
        lblInstruction3 = new javax.swing.JLabel();
        txtQuest3 = new javax.swing.JTextField();
        lblQuestion3Out = new javax.swing.JLabel();
        lblInstruction4 = new javax.swing.JLabel();
        txtQuest4 = new javax.swing.JTextField();
        lblQuestion4Out = new javax.swing.JLabel();
        lblInstruction5 = new javax.swing.JLabel();
        lblInstruction6 = new javax.swing.JLabel();
        txtQuest6 = new javax.swing.JTextField();
        txtQuest5 = new javax.swing.JTextField();
        lblQuestion5Out = new javax.swing.JLabel();
        lblQuestion6Out = new javax.swing.JLabel();
        btnIntToDouble = new javax.swing.JButton();
        btnDoubleToInt = new javax.swing.JButton();
        btnCharToString = new javax.swing.JButton();
        btnStringToChar = new javax.swing.JButton();
        btnStringToInt = new javax.swing.JButton();
        btnStringToDouble = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setText("Type Casting");

        lblInstruction1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction1.setText("Enter a whole number to be displayed as a Double:");

        txtQuest1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQuest1Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuest1Out.setText("...");

        lblInstruction2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction2.setText("Enter a decimal number to be displayed as an Integer:");

        txtQuest2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQuestion2Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuestion2Out.setText("...");

        lblInstruction3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction3.setText("Enter a single character to be displayed as a String:");

        txtQuest3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQuestion3Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuestion3Out.setText("...");

        lblInstruction4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction4.setText("Enter a name and the first letter will be displayed:");

        txtQuest4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQuestion4Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuestion4Out.setText("...");

        lblInstruction5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction5.setText("Enter a whole number to be displayed as an Integer:");

        lblInstruction6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInstruction6.setText("Enter a decimal number to be displayed as a Double:");

        txtQuest6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtQuest5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQuestion5Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuestion5Out.setText("...");

        lblQuestion6Out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQuestion6Out.setText("...");

        btnIntToDouble.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnIntToDouble.setText("Double");
        btnIntToDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntToDoubleActionPerformed(evt);
            }
        });

        btnDoubleToInt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDoubleToInt.setText("Integer");
        btnDoubleToInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleToIntActionPerformed(evt);
            }
        });

        btnCharToString.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCharToString.setText("String");
        btnCharToString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharToStringActionPerformed(evt);
            }
        });

        btnStringToChar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnStringToChar.setText("1st Char");
        btnStringToChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStringToCharActionPerformed(evt);
            }
        });

        btnStringToInt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnStringToInt.setText("Integer");
        btnStringToInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStringToIntActionPerformed(evt);
            }
        });

        btnStringToDouble.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnStringToDouble.setText("Double");
        btnStringToDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStringToDoubleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuest6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuest5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuest4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuest3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuest2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruction1)
                        .addGap(54, 54, 54)
                        .addComponent(txtQuest1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStringToChar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCharToString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoubleToInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIntToDouble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStringToInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStringToDouble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion3Out)
                    .addComponent(lblQuest1Out)
                    .addComponent(lblQuestion2Out)
                    .addComponent(lblQuestion4Out)
                    .addComponent(lblQuestion5Out)
                    .addComponent(lblQuestion6Out))
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(259, 259, 259))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction1)
                    .addComponent(txtQuest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuest1Out)
                    .addComponent(btnIntToDouble))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction2)
                    .addComponent(lblQuestion2Out)
                    .addComponent(txtQuest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoubleToInt))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction3)
                    .addComponent(txtQuest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion3Out)
                    .addComponent(btnCharToString))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction4)
                    .addComponent(txtQuest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion4Out)
                    .addComponent(btnStringToChar))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction5)
                    .addComponent(txtQuest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion5Out)
                    .addComponent(btnStringToInt))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruction6)
                    .addComponent(txtQuest6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion6Out)
                    .addComponent(btnStringToDouble))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntToDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntToDoubleActionPerformed
        // Store input as an integer
        int Stored = Integer.parseInt(txtQuest1.getText());
        //convert value stored to a double
        double StoredOut =(double)Stored;
        //display the converted value
        lblQuest1Out.setText(String.valueOf(StoredOut));
    }//GEN-LAST:event_btnIntToDoubleActionPerformed

    private void btnDoubleToIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleToIntActionPerformed
        // Store input as a double
        double Stored = Double.parseDouble(txtQuest2.getText());
        //cast value stored to an integer
        int StoredOut = (int)Stored;
        //display the converted value
        lblQuestion2Out.setText(String.valueOf(StoredOut));
    }//GEN-LAST:event_btnDoubleToIntActionPerformed

    private void btnCharToStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharToStringActionPerformed
        // Store input as a single character
        char Stored = txtQuest3.getText().charAt(0);
        //cast value stored to a String
        String StoredOut = String.valueOf(Stored);
        //display converted value
        lblQuestion3Out.setText(StoredOut);
    }//GEN-LAST:event_btnCharToStringActionPerformed

    private void btnStringToCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStringToCharActionPerformed
        // Store input as a String
        String Stored = txtQuest4.getText();
        //cast value stored to the first character
        char StoredOut = Stored.charAt(0);
        //display converted value
        lblQuestion4Out.setText(String.valueOf(StoredOut));
    }//GEN-LAST:event_btnStringToCharActionPerformed

    private void btnStringToIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStringToIntActionPerformed
        // Store input as a String
        String Stored = txtQuest5.getText();
        //cast value stored to an integer
        int StoredOut = Integer.parseInt(Stored);
        //display converted value
        lblQuestion5Out.setText(String.valueOf(StoredOut));
    }//GEN-LAST:event_btnStringToIntActionPerformed

    private void btnStringToDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStringToDoubleActionPerformed
        // Store input as a String
        String Stored = txtQuest6.getText();
        //cast value stored to a double
        double StoredOut = Double.parseDouble(Stored);
        //display converted value
        lblQuestion6Out.setText(String.valueOf(StoredOut));
    }//GEN-LAST:event_btnStringToDoubleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTypeCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTypeCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTypeCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTypeCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTypeCasting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharToString;
    private javax.swing.JButton btnDoubleToInt;
    private javax.swing.JButton btnIntToDouble;
    private javax.swing.JButton btnStringToChar;
    private javax.swing.JButton btnStringToDouble;
    private javax.swing.JButton btnStringToInt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInstruction1;
    private javax.swing.JLabel lblInstruction2;
    private javax.swing.JLabel lblInstruction3;
    private javax.swing.JLabel lblInstruction4;
    private javax.swing.JLabel lblInstruction5;
    private javax.swing.JLabel lblInstruction6;
    private javax.swing.JLabel lblQuest1Out;
    private javax.swing.JLabel lblQuestion2Out;
    private javax.swing.JLabel lblQuestion3Out;
    private javax.swing.JLabel lblQuestion4Out;
    private javax.swing.JLabel lblQuestion5Out;
    private javax.swing.JLabel lblQuestion6Out;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtQuest1;
    private javax.swing.JTextField txtQuest2;
    private javax.swing.JTextField txtQuest3;
    private javax.swing.JTextField txtQuest4;
    private javax.swing.JTextField txtQuest5;
    private javax.swing.JTextField txtQuest6;
    // End of variables declaration//GEN-END:variables
}
